<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [ ]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [ ]:
%%sql

select * from sales limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00
5,1002,2,2015-01-01,2015-01-01,1518349,660,1050,3,499.20,434.30,229.57,USD,1.00
6,1002,3,2015-01-01,2015-01-01,1518349,660,1608,1,65.99,58.73,33.65,USD,1.00
7,1003,0,2015-01-01,2015-01-01,1317097,510,85,3,74.99,74.99,34.48,USD,1.00
8,1004,0,2015-01-01,2015-01-01,254117,80,128,2,114.72,113.57,58.49,CAD,1.16
9,1004,1,2015-01-01,2015-01-01,254117,80,2079,1,499.45,499.45,165.48,CAD,1.16

In [28]:
%%sql
Select table_name
from information_schema.tables
where table_schema = 'public';

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

6 rows affected.

         table_name
0  currencyexchange
1          customer
2             sales
3              date
4           product
5             store

In [ ]:
%%sql

select * from sales
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1000,0,2015-01-01,2015-01-01,947009,400,48,1,112.46,98.97,57.34,GBP,0.64
1,1000,1,2015-01-01,2015-01-01,947009,400,460,1,749.75,659.78,382.25,GBP,0.64
2,1001,0,2015-01-01,2015-01-01,1772036,430,1730,2,54.38,54.38,25.00,USD,1.00
3,1002,0,2015-01-01,2015-01-01,1518349,660,955,4,315.04,286.69,144.88,USD,1.00
4,1002,1,2015-01-01,2015-01-01,1518349,660,62,7,135.75,135.75,62.43,USD,1.00

In [ ]:
%%sql

select * from store
limit 3

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

,storekey,storecode,geoareakey,countrycode,countryname,state,opendate,closedate,description,squaremeters,status
0,10,1,1,AU,Australia,Australian Capital Territory,2008-01-01,None,Contoso Store Australian Capital Territory,595.00,None
1,20,2,3,AU,Australia,Northern Territory,2008-01-12,2016-07-07,Contoso Store Northern Territory,665.00,Closed
2,30,3,5,AU,Australia,South Australia,2012-01-07,2015-08-08,Contoso Store South Australia,2000.00,Restructured

In [ ]:
%%sql

select * from product
limit 3

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

,productkey,productcode,productname,manufacturer,brand,color,weightunit,weight,cost,price,categorykey,categoryname,subcategorykey,subcategoryname
0,1,101001,Contoso 512MB MP3 Player E51 Silver,"Contoso, Ltd",Contoso,Silver,ounces,4.80,6.62,12.99,1,Audio,101,MP4&MP3
1,2,101002,Contoso 512MB MP3 Player E51 Blue,"Contoso, Ltd",Contoso,Blue,ounces,4.10,6.62,12.99,1,Audio,101,MP4&MP3
2,3,101003,Contoso 1G MP3 Player E100 White,"Contoso, Ltd",Contoso,White,ounces,4.50,7.40,14.52,1,Audio,101,MP4&MP3

In [ ]:
%%sql

select * from customer
limit 3

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

,customerkey,geoareakey,startdt,enddt,continent,gender,title,givenname,middleinitial,surname,...,zipcode,country,countryfull,birthday,age,occupation,company,vehicle,latitude,longitude
0,15,4,1990-09-10,2034-07-29,Australia,male,Mr.,Julian,A,McGuigan,...,4357,AU,Australia,1965-03-24,55,Border Patrol agent,Cut Rite Lawn Care,2000 Peugeot Kart Up,-27.83,151.17
1,23,8,1995-08-11,2045-01-26,Australia,female,Ms.,Rose,H,Dash,...,6055,AU,Australia,1990-05-10,30,Agricultural and food scientist,Rack N Sack,2005 Volvo XC90,-31.92,116.05
2,36,2,1992-03-12,2044-05-14,Australia,female,Ms.,Annabelle,J,Townsend,...,2304,AU,Australia,1964-07-16,56,Special education teacher,id Boutiques,1999 Lancia Lybra,-32.88,151.71

In [ ]:
%%sql

select * from date
limit 3

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

,date,datekey,year,yearquarter,yearquarternumber,quarter,yearmonth,yearmonthshort,yearmonthnumber,month,monthshort,monthnumber,dayofweek,dayofweekshort,dayofweeknumber,workingday,workingdaynumber
0,2015-01-01,20150101,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Thursday,Thu,5,0,0
1,2015-01-02,20150102,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Friday,Fri,6,1,1
2,2015-01-03,20150103,2015,Q1-2015,8061,Q1,January 2015,Jan 2015,24181,January,Jan,1,Saturday,Sat,7,0,1

In [ ]:
%%sql
Select *
from information_schema.columns
where table_name = 'customer'
limit 2

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

2 rows affected.

,table_catalog,table_schema,table_name,column_name,ordinal_position,column_default,is_nullable,data_type,character_maximum_length,character_octet_length,...,is_identity,identity_generation,identity_start,identity_increment,identity_maximum,identity_minimum,identity_cycle,is_generated,generation_expression,is_updatable
0,contoso_100k,public,customer,customerkey,1,None,NO,integer,None,None,...,NO,None,None,None,None,None,NO,NEVER,None,YES
1,contoso_100k,public,customer,geoareakey,2,None,YES,integer,None,None,...,NO,None,None,None,None,None,NO,NEVER,None,YES

In [ ]:
%%sql

select s.productkey , s.orderdate ,  s.quantity * s.netprice * s.exchangerate as net_revenue,
c.givenname || ' '|| c.surname as fullname, c.countryfull , c.continent , EXTRACT( year from AGE(c.birthday)) as age,
p.productkey , p.productname , p.categoryname , p.subcategoryname
from sales s
left join customer c on c.customerkey = s.customerkey
left join product p on p.productkey = s.productkey
where orderdate::DATE >= '2020-01-01'
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,productkey,orderdate,net_revenue,fullname,countryfull,continent,age,productkey,productname,categoryname,subcategoryname
0,1810,2020-01-01,99.47,Heike Burger,Germany,Europe,39,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games
1,1809,2020-01-01,139.97,Heike Burger,Germany,Europe,39,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games
2,698,2020-01-01,669.39,Heike Burger,Germany,Europe,39,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax"
3,364,2020-01-01,4090.60,Heike Burger,Germany,Europe,39,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops
4,1288,2020-01-01,237.15,Michelle Seeber,Canada,North America,49,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories

# New section High Value customers

In [ ]:
%%sql

select s.productkey , s.orderdate ,  s.quantity * s.netprice * s.exchangerate as net_revenue,
c.givenname || ' '|| c.surname as fullname, c.countryfull , c.continent , EXTRACT( year from AGE(c.birthday)) as age,
p.productkey , p.productname , p.categoryname , p.subcategoryname,
case when (s.quantity * s.netprice * s.exchangerate) > 1000  then 'HighValue' else 'Standard' end as high_standard
from sales s
left join customer c on c.customerkey = s.customerkey
left join product p on p.productkey = s.productkey
where orderdate::DATE >= '2020-01-01'
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

,productkey,orderdate,net_revenue,fullname,countryfull,continent,age,productkey,productname,categoryname,subcategoryname,high_standard
0,1810,2020-01-01,99.47,Heike Burger,Germany,Europe,39,1810,MGS Bicycle Card Games2009 E166,Games and Toys,Download Games,Standard
1,1809,2020-01-01,139.97,Heike Burger,Germany,Europe,39,1809,MGS Bicycle Board Games2009 E165,Games and Toys,Download Games,Standard
2,698,2020-01-01,669.39,Heike Burger,Germany,Europe,39,698,Proseware Wireless Photo All-in-One Printer M3...,Computers,"Printers, Scanners & Fax",Standard
3,364,2020-01-01,4090.60,Heike Burger,Germany,Europe,39,364,Adventure Works Laptop12 M1200 Black,Computers,Laptops,HighValue
4,1288,2020-01-01,237.15,Michelle Seeber,Canada,North America,49,1288,Contoso Genuine Leather Grip Belt E322 Silver,Cameras and camcorders,Cameras & Camcorders Accessories,Standard

# Pivoting Data

In [ ]:
%%sql

select orderdate , count( distinct customerkey) as total_customers
from sales
where orderdate between '2023-01-01' and '2023-12-31'
group by orderdate
order by 1
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

    orderdate  total_customers
0  2023-01-01               12
1  2023-01-02               49
2  2023-01-03               64
3  2023-01-04               78
4  2023-01-05               87

In [ ]:
%%sql

select distinct continent from customer

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

3 rows affected.

       continent
0         Europe
1  North America
2      Australia

In [ ]:
%%sql

select s.orderdate ,
count( distinct s.customerkey) as total_customers,
count(distinct case when c.continent = 'Europe' then s.customerkey end ) as EU_customers,
count(distinct case when c.continent = 'North America' then s.customerkey end ) as NA_customers,
count(distinct case when c.continent = 'Australia' then s.customerkey end ) as AU_customers
from sales s
left join customer c on s.customerkey = c.customerkey
where
  s.orderdate between '2023-01-01' and '2023-12-31'
group by
   s.orderdate
order by 1

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

364 rows affected.

      orderdate  total_customers  eu_customers  na_customers  au_customers
0    2023-01-01               12             6             5             1
1    2023-01-02               49            15            31             3
2    2023-01-03               64            17            44             3
3    2023-01-04               78            28            46             4
4    2023-01-05               87            22            57             8
..          ...              ...           ...           ...           ...
359  2023-12-27               73            26            41             6
360  2023-12-28               75            24            44             7
361  2023-12-29               55            19            32             4
362  2023-12-30               91            25            50            16
363  2023-12-31                9             1             8             0

[364 rows x 5 columns]

In [ ]:
%%sql

select
  p.categoryname ,
  sum(s.quantity * s.netprice * s.exchangerate) as net_revenue,
  sum(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end ) as total_net_rev2022,
    sum(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end ) as total_net_rev2023
from
  sales s
left join product p on s.productkey = p.productkey
group by
   p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,net_revenue,total_net_rev2022,total_net_rev2023
0,Audio,5312898.10,766938.21,688690.18
1,Cameras and camcorders,18520360.66,2382532.56,1983546.29
2,Cell phones,32624265.72,8119665.07,6002147.63
3,Computers,90619022.05,17862213.49,11650867.21
4,Games and Toys,1668574.13,316127.30,270374.96
5,Home Appliances,26607245.54,6612446.68,5919992.87
6,"Music, Movies and Audio Books",10588311.00,2989297.28,2180768.13
7,TV and Video,20466861.38,5815336.61,4412178.23

# Statistical Aggregations

In [ ]:
%%sql

select
  p.categoryname ,
  avg(case when s.orderdate between '2022-01-01' and '2022-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end ) as Avg_net_rev2022,
  avg(case when s.orderdate between '2023-01-01' and '2023-12-31' then s.quantity * s.netprice * s.exchangerate else 0 end ) as Avg_net_rev2023
from
  sales s
left join product p on s.productkey = p.productkey
group by
   p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                    categoryname  avg_net_rev2022  avg_net_rev2023
0                          Audio            50.18            45.06
1        Cameras and camcorders            176.85           147.23
2                    Cell phones           194.66           143.89
3                      Computers           384.13           250.55
4                 Games and Toys            15.60            13.34
5                Home Appliances           390.05           349.20
6  Music, Movies and Audio Books            93.37            68.11
7                   TV and Video           425.35           322.72

In [ ]:
%%sql

select
  p.categoryname ,
  avg(case when s.orderdate between '2022-01-01' and '2022-12-31'
  then (s.quantity * s.netprice * s.exchangerate)  end ) as Avg_net_rev2022,
  avg(case when s.orderdate between '2023-01-01' and '2023-12-31'
   then (s.quantity * s.netprice * s.exchangerate)end ) as Avg_net_rev2023,
  MIN(case when s.orderdate between '2022-01-01' and '2022-12-31'
   then (s.quantity * s.netprice * s.exchangerate)end ) as Min_net_rev2022,
  MIN(case when s.orderdate between '2023-01-01' and '2023-12-31'
   then (s.quantity * s.netprice * s.exchangerate)end ) as Min_net_rev2023,
  MAX(case when s.orderdate between '2022-01-01' and '2022-12-31'
   then (s.quantity * s.netprice * s.exchangerate)end ) as Max_net_rev2022,
  MAX(case when s.orderdate between '2023-01-01' and '2023-12-31'
   then (s.quantity * s.netprice * s.exchangerate)end ) as Max_net_rev2023
from
  sales s
left join product p on s.productkey = p.productkey
group by
   p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,categoryname,avg_net_rev2022,avg_net_rev2023,min_net_rev2022,min_net_rev2023,max_net_rev2022,max_net_rev2023
0,Audio,392.30,425.38,9.31,10.85,3473.36,2730.87
1,Cameras and camcorders,1210.02,1210.96,6.74,5.98,15008.39,13572.00
2,Cell phones,722.20,623.28,2.53,2.28,7692.37,8912.22
3,Computers,1565.62,1292.39,0.83,0.75,38082.66,27611.60
4,Games and Toys,81.29,80.83,2.83,3.49,5202.01,3357.30
5,Home Appliances,1755.36,1886.55,4.04,4.54,31654.55,32915.59
6,"Music, Movies and Audio Books",386.61,334.58,7.29,6.91,5415.19,3804.91
7,TV and Video,1535.61,1687.90,41.30,42.30,30259.41,27503.12

# Median

In [ ]:
%%sql

select
PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY netprice) as median_price
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median_price
0        191.95

In [ ]:
%%sql

select
avg(netprice) as avg_price
from sales

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   avg_price
0     324.30

In [ ]:
%%sql

select
  p.categoryname as category,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY
  (case when s.orderdate between '2022-01-01' and '2022-12-31' then (s.quantity * s.netprice * s.exchangerate) end )) as y2022_median_sales,
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY
  (case when s.orderdate between '2023-01-01' and '2023-12-31' then (s.quantity * s.netprice * s.exchangerate) end )) as y2023_median_sales
from
  sales s
left join product p on s.productkey = p.productkey
group by
   p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

                        category  y2022_median_sales  y2023_median_sales
0                          Audio              257.21              266.59
1        Cameras and camcorders               651.46              672.60
2                    Cell phones              418.60              375.88
3                      Computers              809.70              657.18
4                 Games and Toys               33.78               32.62
5                Home Appliances              791.00              825.25
6  Music, Movies and Audio Books              186.58              159.63
7                   TV and Video              730.46              790.79

# Segmentation

In [ ]:
%%sql

select
  orderdate,
  quantity,
  netprice,
  case
    when quantity >= 2 and netprice >= 100 then 'Multiple High Value Items'
    When netprice >= 100 then 'Single High Value Item'
    WHEN quantity >=2 then 'Multiple standard items'
    ELSE 'Single standard item' end order_type
from sales
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

    orderdate  quantity  netprice                 order_type
0  2015-01-01         1     98.97       Single standard item
1  2015-01-01         1    659.78     Single High Value Item
2  2015-01-01         2     54.38    Multiple standard items
3  2015-01-01         4    286.69  Multiple High Value Items
4  2015-01-01         7    135.75  Multiple High Value Items

In [ ]:
%%sql

select
  PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) as median
from sales as s
where
  orderdate between '2022-01-01' and '2022-12-31'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

1 rows affected.

   median
0  421.34

In [ ]:
%%sql

with median_value as(
  select
    PERCENTILE_CONT(0.5) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) as median
  from sales as s
)
select
  p.categoryname as category,
  sum(case when (s.quantity * s.netprice * s.exchangerate) < mv.median
        and s.orderdate between '2022-01-01' and '2022-12-31'
     then (s.quantity * s.netprice * s.exchangerate) END ) as low_net_revenue2022,
    sum(case when (s.quantity * s.netprice * s.exchangerate) > mv.median
        and s.orderdate between '2022-01-01' and '2022-12-31'
     then (s.quantity * s.netprice * s.exchangerate) END ) as high_net_revenue2022,
  sum(case when (s.quantity * s.netprice * s.exchangerate) < mv.median
        and s.orderdate between '2023-01-01' and '2023-12-31'
     then (s.quantity * s.netprice * s.exchangerate) END ) as low_net_revenue2023,
    sum(case when (s.quantity * s.netprice * s.exchangerate) > mv.median
        and s.orderdate between '2023-01-01' and '2023-12-31'
     then (s.quantity * s.netprice * s.exchangerate) END ) as high_net_revenue2023
from
  sales s
left join product p on s.productkey = p.productkey,
median_value as mv
group by
   p.categoryname
order by p.categoryname

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

8 rows affected.

,category,low_net_revenue2022,high_net_revenue2022,low_net_revenue2023,high_net_revenue2023
0,Audio,223932.63,543005.58,181847.01,506843.18
1,Cameras and camcorders,133801.07,2248731.49,105268.50,1878277.79
2,Cell phones,822810.73,7296854.34,738857.59,5263290.05
3,Computers,626333.55,17235480.77,592385.19,11058482.02
4,Games and Toys,232378.35,83748.95,206103.36,64271.60
5,Home Appliances,220196.04,6392250.64,177059.16,5742933.71
6,"Music, Movies and Audio Books",687403.38,2301893.90,576552.89,1604215.24
7,TV and Video,273532.94,5541803.66,166265.95,4245912.27

In [42]:
%%sql

With Percentile as(
select
  PERCENTILE_CONT(0.25) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) as revenue_25th_percentile,
  PERCENTILE_CONT(0.75) WITHIN GROUP (ORDER BY (s.quantity * s.netprice * s.exchangerate)) as revenue_75th_percentile
from sales as s
where
  orderdate between '2022-01-01' and '2022-12-31'
)

select
  p.categoryname as category,
CASE
  WHEN (s.quantity * s.netprice * s.exchangerate) <=   revenue_25th_percentile then '3 - Low'
  WHEN (s.quantity * s.netprice * s.exchangerate) >=   revenue_75th_percentile then '1 - High'
  else '2 - Mid' end as RevenueTier,
  sum(s.quantity * s.netprice * s.exchangerate) as total_revenue
from
  sales s
left join product p on s.productkey = p.productkey
cross join Percentile pctl
group by
   p.categoryname,
   RevenueTier
order by p.categoryname, RevenueTier
limit 5

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

5 rows affected.

                  category revenuetier  total_revenue
0                    Audio    1 - High     1089077.23
1                    Audio     2 - Mid     3923515.28
2                    Audio     3 - Low      300305.59
3  Cameras and camcorders     1 - High    14812098.11
4  Cameras and camcorders      2 - Mid     3620129.66

# Date and Time Transformations